### ISSUE TITLE
support WeScrollView

### ISSUE THREAD

**Issue by yt8jbe7q63** [charlesmchen/WeView2#2]
I want to show multiple WeViews (stacked vertically one after another). And one of them needs to be scrollable when needed. So I created a subclass of UIScrollView and added an instance of WeView as its only subview, and then added multiple instances of UILabel to the WeView just to see if this would work as expected. But unfortunately those UILabel instances were squeezed into the visible area of the WeView instance. No vertical scroll bar is shown. 

It would be nice to have WeScrollView that doesn't squeeze everything into the visible area. And with WeScrollView, I won't need to add an instance of WeView into the subclass of UIScrollView. Thanks.

**Comment by charlesmchen** [comment]
This has been done.

See: https://github.com/charlesmchen/WeView2/commit/a465c8c1d986116ac5e5d2aec72aa0033a35054e

Thanks @rjansen72 yt8jbe7q63

**Comment by charlesmchen** [comment]
This has been done.

See: https://github.com/charlesmchen/WeView2/commit/a465c8c1d986116ac5e5d2aec72aa0033a35054e

Thanks @rjansen72 @yt8jbe7q63
